import type { Localized } from "../i18n/locale";

export type ChapterStatus = "transmitted" | "incoming" | "sealed";

export interface Chapter {
  /** Position in the arc, as defined in README -> THE LAST SIGNAL. */
  id: number;
  status: ChapterStatus;
  /** The stage name from the canonical story structure. */
  stage: Localized<string>;
  title: Localized<string>;
  /** Shown for every chapter, including sealed ones. */
  teaser: Localized<string>;
  /** Full text. Only written once a chapter has actually been transmitted. */
  body?: Localized<string[]>;
}

export const chapters: Chapter[] = [
  {
    id: 1,
    status: "transmitted",
    stage: {
      en: "Unknown Signal", fa: "سیگنال ناشناس", ar: "إشارة مجهولة",
      ur: "نامعلوم سگنل", hi: "अज्ञात सिग्नल", tr: "Bilinmeyen Sinyal",
      az: "Naməlum Siqnal", zh: "未知信号",
    },
    title: {
      en: "Something Answered", fa: "چیزی پاسخ داد", ar: "شيء ما أجاب",
      ur: "کسی چیز نے جواب دیا", hi: "किसी ने उत्तर दिया",
      tr: "Bir Şey Cevap Verdi", az: "Nəsə Cavab Verdi", zh: "有什么回应了",
    },
    teaser: {
      en: "A signal reaches Earth. Nobody sent it.",
      fa: "سیگنالی به زمین می‌رسد. هیچ‌کس آن را نفرستاده است.",
      ar: "إشارة تصل إلى الأرض. لم يرسلها أحد.",
      ur: "ایک سگنل زمین تک پہنچتا ہے۔ اسے کسی نے نہیں بھیجا۔",
      hi: "एक सिग्नल पृथ्वी तक पहुँचता है। इसे किसी ने नहीं भेजा।",
      tr: "Bir sinyal Dünya'ya ulaşıyor. Kimse göndermedi.",
      az: "Bir siqnal Yerə çatır. Onu heç kim göndərməyib.",
      zh: "一个信号抵达地球。没有人发出它。",
    },
    body: {
      en: [
        "It arrived on a Tuesday, at 03:17 UTC, on a frequency nobody uses any more.",
        "Seventeen stations recorded it. None of them were listening for it. The pattern held for four minutes and eleven seconds, then stopped — not faded, stopped, the way a sentence stops when the speaker decides you have heard enough.",
        "It has not repeated. What it left behind is a fragment: incomplete, structured, and clearly meant to be finished by someone else.",
        "That is where MOLIDO begins. Not with an answer — with the first piece of a question.",
      ],
      ar: [
        "وصلت يوم ثلاثاء، الساعة ٠٣:١٧ بالتوقيت العالمي، على تردد لم يعد أحد يستخدمه.",
        "سجّلتها سبع عشرة محطة. لم تكن أي منها تنصت إليها. استمر النمط أربع دقائق وإحدى عشرة ثانية، ثم توقف — لم يخفت، بل توقف، كما تتوقف جملة حين يقرر المتحدث أنك سمعت ما يكفي.",
        "لم تتكرر. ما خلّفته وراءها شظية: ناقصة، منظّمة، ومقصود بوضوح أن يُكملها شخص آخر.",
        "من هنا يبدأ موليدو. لا بجواب — بل بأول قطعة من سؤال.",
      ],
      ur: [
        "یہ منگل کو آیا، عالمی وقت کے مطابق ۰۳:۱۷ بجے، ایک ایسی فریکوئنسی پر جسے اب کوئی استعمال نہیں کرتا۔",
        "سترہ اسٹیشنوں نے اسے ریکارڈ کیا۔ ان میں سے کوئی بھی اس کے انتظار میں نہ تھا۔ ترتیب چار منٹ گیارہ سیکنڈ قائم رہی، پھر رک گئی — مدھم نہیں ہوئی، رک گئی، جیسے جملہ اس وقت رکتا ہے جب بولنے والا طے کر لے کہ آپ کافی سن چکے۔",
        "یہ دوبارہ نہیں آیا۔ جو پیچھے چھوڑ گیا وہ ایک ٹکڑا ہے: نامکمل، منظم، اور واضح طور پر اس ارادے سے بنا کہ کوئی اور اسے مکمل کرے۔",
        "مولیڈو یہیں سے شروع ہوتا ہے۔ کسی جواب سے نہیں — ایک سوال کے پہلے ٹکڑے سے۔",
      ],
      hi: [
        "यह मंगलवार को आया, वैश्विक समय 03:17 पर, एक ऐसी आवृत्ति पर जिसे अब कोई इस्तेमाल नहीं करता।",
        "सत्रह स्टेशनों ने इसे दर्ज किया। उनमें से कोई भी इसकी प्रतीक्षा में नहीं था। पैटर्न चार मिनट ग्यारह सेकंड तक बना रहा, फिर रुक गया — धुँधला नहीं पड़ा, रुक गया, जैसे कोई वाक्य तब रुकता है जब बोलने वाला तय कर ले कि आपने पर्याप्त सुन लिया।",
        "यह दोहराया नहीं गया। पीछे जो छूटा वह एक टुकड़ा है: अधूरा, संरचित, और स्पष्ट रूप से इस मंशा से बना कि कोई और इसे पूरा करे।",
        "मोलिडो यहीं से शुरू होता है। किसी उत्तर से नहीं — एक प्रश्न के पहले टुकड़े से।",
      ],
      tr: [
        "Bir salı günü geldi, evrensel saatle 03:17'de, artık kimsenin kullanmadığı bir frekansta.",
        "On yedi istasyon kaydetti. Hiçbiri onu dinlemiyordu. Örüntü dört dakika on bir saniye sürdü, sonra durdu — sönmedi, durdu; bir cümlenin, konuşan kişi yeterince duyduğunuza karar verdiğinde durduğu gibi.",
        "Tekrarlanmadı. Geride bıraktığı şey bir parça: eksik, yapılı ve açıkça başkası tarafından tamamlanmak üzere bırakılmış.",
        "MOLIDO işte burada başlıyor. Bir cevapla değil — bir sorunun ilk parçasıyla.",
      ],
      az: [
        "Çərşənbə axşamı gəldi, ümumdünya vaxtı ilə 03:17-də, artıq heç kimin istifadə etmədiyi bir tezlikdə.",
        "On yeddi stansiya onu qeydə aldı. Heç biri onu dinləmirdi. Naxış dörd dəqiqə on bir saniyə davam etdi, sonra dayandı — sönmədi, dayandı; cümlə danışan adam kifayət qədər eşitdiyinizə qərar verəndə necə dayanırsa, elə.",
        "Təkrarlanmadı. Geridə qoyduğu bir parçadır: yarımçıq, quruluşlu və açıq-aşkar başqası tərəfindən tamamlanmaq üçün buraxılmış.",
        "MOLIDO məhz buradan başlayır. Cavabla yox — sualın ilk parçası ilə.",
      ],
      zh: [
        "它在一个星期二抵达，世界时 03:17，用的是一个再没人使用的频率。",
        "十七个台站记录到了它。没有一个是在守听它。图样持续了四分十一秒，然后停止——不是渐弱，是停止，就像说话的人认定你已经听够了，一句话就此打住。",
        "它没有重复。留下来的是一个片段：不完整，有结构，而且显然是留给别人来补完的。",
        "MOLIDO 就从这里开始。不是从一个答案——而是从一个问题的第一块碎片。",
      ],
      fa: [
        "سه‌شنبه رسید، ساعت ۰۳:۱۷ به وقت جهانی، روی فرکانسی که دیگر کسی از آن استفاده نمی‌کند.",
        "هفده ایستگاه ثبتش کردند. هیچ‌کدام منتظرش نبودند. الگو چهار دقیقه و یازده ثانیه دوام آورد، بعد قطع شد — نه محو شد، قطع شد؛ همان‌طور که جمله‌ای قطع می‌شود وقتی گوینده تصمیم می‌گیرد به‌اندازه‌ی کافی شنیده‌ای.",
        "تکرار نشده است. آنچه به‌جا گذاشت یک قطعه است: ناقص، ساختارمند، و آشکارا ساخته‌شده تا کس دیگری تمامش کند.",
        "مولیدو از همین‌جا آغاز می‌شود. نه با یک پاسخ — با نخستین تکه‌ی یک پرسش.",
      ],
    },
  },
  {
    id: 2,
    status: "transmitted",
    stage: {
      en: "First Fragment", fa: "نخستین قطعه", ar: "الشظية الأولى",
      ur: "پہلا ٹکڑا", hi: "पहला टुकड़ा", tr: "İlk Parça",
      az: "İlk Parça", zh: "第一个片段",
    },
    title: {
      en: "The Incomplete Message", fa: "پیام ناتمام", ar: "الرسالة الناقصة",
      ur: "نامکمل پیغام", hi: "अधूरा संदेश", tr: "Eksik Mesaj",
      az: "Yarımçıq Mesaj", zh: "不完整的讯息",
    },
    teaser: {
      en: "The fragment is not noise. It is structured — and something is missing from it on purpose.",
      fa: "قطعه نویز نیست. ساختار دارد — و چیزی عمداً از آن کم شده است.",
      ar: "الشظية ليست ضجيجًا. لها بنية — وشيء ناقص فيها عن قصد.",
      ur: "یہ ٹکڑا شور نہیں ہے۔ اس کی ساخت ہے — اور اس میں سے کچھ جان بوجھ کر غائب ہے۔",
      hi: "यह टुकड़ा शोर नहीं है। इसकी संरचना है — और इसमें से कुछ जानबूझकर गायब है।",
      tr: "Parça gürültü değil. Yapısı var — ve ondan bir şey bilerek eksik bırakılmış.",
      az: "Parça səs-küy deyil. Quruluşu var — və ondan nəsə qəsdən əskikdir.",
      zh: "这个片段不是噪声。它有结构——而其中缺了一样东西，是故意的。",
    },
    body: {
      en: [
        "Noise is easy to recognise. Noise has no opinion about where it ends.",
        "This has structure. Repeating blocks, consistent spacing, a checksum at the close of each section that resolves correctly — every section except one. In that section the checksum expects fourteen values and receives thirteen.",
        "The obvious reading is damage: something lost in transit, a gap where the atmosphere or the distance ate a piece of the message. But damaged data does not usually leave the surrounding structure intact, and this structure is untouched on both sides of the hole. The gap is the exact size of the thing that should fill it.",
        "Which leaves a harder reading. The fragment was not broken on the way here. It was sent incomplete.",
        "A message you cannot finish is a message. A message that can only be finished by someone doing something is an invitation.",
        "Nobody has decided yet which one this is.",
      ],
      ar: [
        "الضجيج يسهل التعرف عليه. الضجيج لا رأي له في أين ينتهي.",
        "هذه لها بنية. كتل متكررة، تباعد منتظم، ومجموع رقابي في ختام كل قسم يُحَل بشكل صحيح — كل قسم إلا واحدًا. في ذلك القسم يتوقع المجموع الرقابي أربع عشرة قيمة ويتلقى ثلاث عشرة.",
        "القراءة البديهية هي التلف: شيء ضاع في الطريق، فجوة التهم فيها الغلاف الجوي أو المسافة جزءًا من الرسالة. لكن البيانات التالفة لا تترك عادة البنية المحيطة سليمة، وهذه البنية لم تُمَس على جانبي الثقب. الفجوة بالضبط بحجم الشيء الذي ينبغي أن يملأها.",
        "وهذا يترك قراءة أصعب. الشظية لم تنكسر في الطريق إلى هنا. أُرسلت ناقصة.",
        "الرسالة التي لا تستطيع إتمامها رسالة. والرسالة التي لا تكتمل إلا بأن يفعل أحدهم شيئًا دعوة.",
        "لم يقرر أحد بعد أيهما هذه.",
      ],
      ur: [
        "شور کو پہچاننا آسان ہے۔ شور کی اس بارے میں کوئی رائے نہیں ہوتی کہ وہ کہاں ختم ہو۔",
        "اس کی ساخت ہے۔ دہراتے ہوئے بلاک، یکساں وقفے، اور ہر حصے کے اختتام پر ایک چیک سم جو درست حل ہوتا ہے — ایک حصے کے سوا۔ اُس حصے میں چیک سم چودہ اقدار کی توقع کرتا ہے اور تیرہ پاتا ہے۔",
        "ظاہری تشریح نقصان ہے: راستے میں کچھ کھو گیا، ایک خلا جہاں فضا یا فاصلے نے پیغام کا ایک ٹکڑا نگل لیا۔ لیکن خراب ڈیٹا عام طور پر گرد و پیش کی ساخت کو سالم نہیں چھوڑتا، اور یہاں سوراخ کے دونوں طرف ساخت اچھوتی ہے۔ خلا بالکل اُتنا ہی بڑا ہے جتنی وہ چیز جو اسے بھرنی چاہیے۔",
        "اس سے ایک مشکل تر تشریح باقی رہتی ہے۔ ٹکڑا یہاں آتے ہوئے ٹوٹا نہیں۔ اسے نامکمل بھیجا گیا۔",
        "وہ پیغام جسے آپ مکمل نہیں کر سکتے، ایک پیغام ہے۔ وہ پیغام جو صرف کسی کے کچھ کرنے سے مکمل ہوتا ہے، ایک دعوت ہے۔",
        "ابھی کسی نے طے نہیں کیا کہ یہ کون سا ہے۔",
      ],
      hi: [
        "शोर को पहचानना आसान है। शोर की इस बारे में कोई राय नहीं होती कि वह कहाँ समाप्त हो।",
        "इसकी संरचना है। दोहराते हुए खंड, एक-सा अंतराल, और हर भाग के अंत में एक चेकसम जो सही हल होता है — एक भाग को छोड़कर। उस भाग में चेकसम चौदह मानों की अपेक्षा करता है और तेरह पाता है।",
        "स्पष्ट व्याख्या क्षति है: रास्ते में कुछ खो गया, एक अंतराल जहाँ वायुमंडल या दूरी ने संदेश का एक हिस्सा निगल लिया। परंतु क्षतिग्रस्त डेटा प्रायः आसपास की संरचना को अक्षत नहीं छोड़ता, और यहाँ छेद के दोनों ओर संरचना अछूती है। अंतराल ठीक उतना ही बड़ा है जितनी वह चीज़ जो उसे भरनी चाहिए।",
        "इससे एक कठिन व्याख्या शेष रहती है। टुकड़ा यहाँ आते हुए टूटा नहीं। इसे अधूरा भेजा गया।",
        "वह संदेश जिसे आप पूरा नहीं कर सकते, एक संदेश है। वह संदेश जो केवल किसी के कुछ करने से पूरा होता है, एक निमंत्रण है।",
        "अभी किसी ने तय नहीं किया कि यह कौन-सा है।",
      ],
      tr: [
        "Gürültüyü tanımak kolaydır. Gürültünün nerede biteceği konusunda bir fikri yoktur.",
        "Bunun yapısı var. Tekrarlayan bloklar, düzenli aralıklar ve her bölümün sonunda doğru çözülen bir sağlama — biri hariç her bölümde. O bölümde sağlama on dört değer bekliyor ve on üç alıyor.",
        "Bariz okuma hasardır: yolda kaybolan bir şey, atmosferin ya da mesafenin mesajdan bir parça yediği bir boşluk. Ama bozulmuş veri genellikle çevresindeki yapıyı sağlam bırakmaz; burada ise deliğin iki yanında da yapıya dokunulmamış. Boşluk, tam olarak onu dolduracak şeyin boyutunda.",
        "Geriye daha zor bir okuma kalıyor. Parça buraya gelirken kırılmadı. Eksik gönderildi.",
        "Tamamlayamadığın bir mesaj, bir mesajdır. Yalnızca birinin bir şey yapmasıyla tamamlanabilen bir mesaj ise bir davettir.",
        "Bunun hangisi olduğuna henüz kimse karar vermedi.",
      ],
      az: [
        "Səs-küyü tanımaq asandır. Səs-küyün harada bitəcəyi barədə fikri olmur.",
        "Bunun quruluşu var. Təkrarlanan bloklar, bərabər aralıqlar və hər bölmənin sonunda düzgün həll olunan bir yoxlama məbləği — biri istisna olmaqla hər bölmədə. O bölmədə yoxlama on dörd dəyər gözləyir və on üç alır.",
        "Aşkar oxunuş zədədir: yolda itən nəsə, atmosferin və ya məsafənin mesajdan bir parça uddığı boşluq. Lakin zədələnmiş məlumat adətən ətrafdakı quruluşu toxunulmaz qoymur, burada isə deşiyin hər iki tərəfində quruluş salamatdır. Boşluq tam olaraq onu dolduracaq şeyin ölçüsündədir.",
        "Geriyə daha çətin bir oxunuş qalır. Parça bura gələrkən qırılmayıb. Yarımçıq göndərilib.",
        "Tamamlaya bilmədiyin mesaj, bir mesajdır. Yalnız kiminsə nəsə etməsi ilə tamamlanan mesaj isə bir dəvətdir.",
        "Bunun hansı olduğuna hələ heç kim qərar verməyib.",
      ],
      zh: [
        "噪声很容易辨认。噪声对自己在哪里结束没有意见。",
        "这个有结构。重复的区块，一致的间距，每一节末尾都有一个能正确解出的校验和——除了一节。在那一节里，校验和期待十四个值，收到的是十三个。",
        "显而易见的解读是损坏：途中丢了什么，大气或距离吃掉了讯息的一块。但损坏的数据通常不会让周围的结构完好无损，而这里，缺口两侧的结构都未被触碰。缺口的大小，恰好就是本该填进去的那样东西的大小。",
        "于是剩下一种更难接受的解读。片段不是在来的路上碎的。它是被不完整地发出的。",
        "一条你无法补完的讯息，是一条讯息。一条只有靠某人去做点什么才能补完的讯息，是一份邀请。",
        "还没有人断定这是哪一种。",
      ],
      fa: [
        "نویز را به‌راحتی می‌شود تشخیص داد. نویز درباره‌ی اینکه کجا تمام شود نظری ندارد.",
        "این یکی ساختار دارد. بلوک‌های تکرارشونده، فاصله‌گذاری یکنواخت، و یک جمع کنترلی در پایان هر بخش که درست حل می‌شود — همه‌ی بخش‌ها جز یکی. در آن بخش، جمع کنترلی انتظار چهارده مقدار را دارد و سیزده مقدار دریافت می‌کند.",
        "خوانش بدیهی، آسیب است: چیزی در مسیر گم شده، شکافی که جوّ یا فاصله تکه‌ای از پیام را خورده. اما داده‌ی آسیب‌دیده معمولاً ساختار پیرامونش را دست‌نخورده باقی نمی‌گذارد، و اینجا ساختار در هر دو سوی حفره سالم است. اندازه‌ی شکاف دقیقاً به‌اندازه‌ی چیزی است که باید پُرش کند.",
        "و این خوانش دشوارتری باقی می‌گذارد. قطعه در راه نشکسته است. ناقص فرستاده شده است.",
        "پیامی که نمی‌توانی تمامش کنی، یک پیام است. پیامی که فقط با انجام‌دادن کاری از سوی کسی تمام می‌شود، یک دعوت است.",
        "هنوز کسی تصمیم نگرفته این کدام یک است.",
      ],
    },
  },
  {
    id: 3,
    status: "transmitted",
    stage: {
      en: "Hidden Coordinates", fa: "مختصات پنهان", ar: "إحداثيات خفية",
      ur: "پوشیدہ کوآرڈینیٹس", hi: "छिपे निर्देशांक", tr: "Gizli Koordinatlar",
      az: "Gizli Koordinatlar", zh: "隐藏的坐标",
    },
    title: {
      en: "A Place That Should Be Empty",
      fa: "جایی که باید خالی باشد",
      ar: "مكان ينبغي أن يكون خاليًا",
      ur: "ایک جگہ جو خالی ہونی چاہیے",
      hi: "एक जगह जो खाली होनी चाहिए",
      tr: "Boş Olması Gereken Bir Yer",
      az: "Boş Olmalı Olan Bir Yer",
      zh: "一个本该空无一物的地方",
    },
    teaser: {
      en: "The fragment resolves to a location. The maps disagree about it.",
      fa: "قطعه به یک موقعیت مکانی می‌رسد. نقشه‌ها بر سر آن اختلاف دارند.",
      ar: "الشظية تُفضي إلى موقع. والخرائط تختلف بشأنه.",
      ur: "ٹکڑا ایک مقام تک پہنچتا ہے۔ نقشے اس پر متفق نہیں۔",
      hi: "टुकड़ा एक स्थान तक पहुँचता है। नक़्शे उस पर सहमत नहीं हैं।",
      tr: "Parça bir konuma çözülüyor. Haritalar bu konuda anlaşamıyor.",
      az: "Parça bir məkana çevrilir. Xəritələr bu barədə razılaşmır.",
      zh: "片段指向一个位置。地图对它意见不一。",
    },
    body: {
      en: [
        "Thirteen values. Read as coordinates, they resolve.",
        "They resolve to open water — a stretch of ocean with nothing on it, which is what most of the planet is. Unremarkable, until you compare sources. Older survey charts mark a small landmass there. Newer ones do not. The correction appears in the record without a survey behind it, the way a typo gets fixed rather than the way a discovery gets made.",
        "There are ordinary explanations. Charts inherit errors from each other for centuries; phantom islands have been copied forward and quietly deleted before. That is the likely answer, and it should be said plainly rather than skipped past because a stranger one is available.",
        "What the ordinary explanation does not cover is the fourteenth value — the one the checksum expects and the fragment does not supply.",
        "Coordinates fix a point on a surface. Thirteen values give a where. The missing one would give a when.",
        "The fragment is not pointing at a place. It is pointing at a place at a time, and it has declined to say which.",
      ],
      ar: [
        "ثلاث عشرة قيمة. إذا قُرئت كإحداثيات، فإنها تُحَل.",
        "تُفضي إلى مياه مفتوحة — امتداد من المحيط لا شيء عليه، وهو ما عليه معظم هذا الكوكب. عادي، حتى تقارن المصادر. الخرائط المساحية الأقدم تُعلّم هناك يابسة صغيرة. الأحدث لا تفعل. ويظهر التصحيح في السجل دون مسح خلفه، بالطريقة التي يُصحَّح بها خطأ مطبعي، لا بالطريقة التي يُسجَّل بها اكتشاف.",
        "ثمة تفسيرات عادية. الخرائط ترث أخطاء بعضها لقرون؛ وقد نُسخت جزر وهمية إلى الأمام ثم حُذفت بهدوء من قبل. هذا هو الجواب المرجّح، وينبغي أن يُقال صراحةً لا أن يُتجاوَز لأن جوابًا أغرب متاح.",
        "ما لا يغطيه التفسير العادي هو القيمة الرابعة عشرة — تلك التي يتوقعها المجموع الرقابي ولا تقدّمها الشظية.",
        "الإحداثيات تثبّت نقطة على سطح. ثلاث عشرة قيمة تعطي «أين». والقيمة الغائبة كانت ستعطي «متى».",
        "الشظية لا تشير إلى مكان. إنها تشير إلى مكان في زمن، وقد امتنعت عن قول أي زمن.",
      ],
      ur: [
        "تیرہ اقدار۔ اگر انہیں کوآرڈینیٹس کے طور پر پڑھا جائے تو وہ حل ہو جاتی ہیں۔",
        "وہ کھلے پانی تک پہنچتی ہیں — سمندر کا ایک پھیلاؤ جس پر کچھ نہیں، جو اس سیارے کا بیشتر حصہ ہے۔ عام سا، جب تک آپ ذرائع کا موازنہ نہ کریں۔ پرانے سروے نقشے وہاں ایک چھوٹی خشکی دکھاتے ہیں۔ نئے نہیں دکھاتے۔ اور یہ تصحیح ریکارڈ میں کسی سروے کے بغیر آ جاتی ہے، اُس طرح جیسے کوئی املا کی غلطی درست کی جائے، نہ کہ اُس طرح جیسے کوئی دریافت درج ہو۔",
        "عام وضاحتیں موجود ہیں۔ نقشے صدیوں تک ایک دوسرے کی غلطیاں وراثت میں لیتے ہیں؛ فرضی جزیرے پہلے بھی آگے نقل ہوتے رہے اور خاموشی سے مٹا دیے گئے۔ یہی ممکنہ جواب ہے، اور اسے صاف کہا جانا چاہیے، نہ کہ اس لیے چھوڑ دیا جائے کہ ایک عجیب تر جواب دستیاب ہے۔",
        "جو چیز عام وضاحت کے دائرے میں نہیں آتی وہ چودھویں قدر ہے — وہی جس کی چیک سم توقع کرتا ہے اور ٹکڑا فراہم نہیں کرتا۔",
        "کوآرڈینیٹس کسی سطح پر ایک نقطہ متعین کرتے ہیں۔ تیرہ اقدار ایک «کہاں» دیتی ہیں۔ غائب قدر ایک «کب» دیتی۔",
        "ٹکڑا کسی جگہ کی طرف اشارہ نہیں کر رہا۔ وہ ایک وقت میں ایک جگہ کی طرف اشارہ کر رہا ہے، اور اس نے بتانے سے انکار کیا ہے کہ کون سا وقت۔",
      ],
      hi: [
        "तेरह मान। यदि उन्हें निर्देशांक के रूप में पढ़ा जाए तो वे हल हो जाते हैं।",
        "वे खुले जल तक पहुँचते हैं — समुद्र का एक विस्तार जिस पर कुछ नहीं, जो इस ग्रह का अधिकांश है। साधारण, जब तक आप स्रोतों की तुलना न करें। पुराने सर्वेक्षण मानचित्र वहाँ एक छोटी भूमि दिखाते हैं। नए नहीं दिखाते। और यह सुधार अभिलेख में बिना किसी सर्वेक्षण के आ जाता है, उस तरह जैसे कोई वर्तनी की भूल सुधारी जाती है, न कि उस तरह जैसे कोई खोज दर्ज होती है।",
        "साधारण व्याख्याएँ मौजूद हैं। मानचित्र सदियों तक एक-दूसरे की त्रुटियाँ विरासत में लेते हैं; काल्पनिक द्वीप पहले भी आगे नकल होते रहे और चुपचाप मिटा दिए गए। यही संभावित उत्तर है, और इसे स्पष्ट कहा जाना चाहिए, न कि इसलिए छोड़ दिया जाए कि एक अजीबतर उत्तर उपलब्ध है।",
        "जो बात साधारण व्याख्या से नहीं ढँकती वह चौदहवाँ मान है — वही जिसकी चेकसम अपेक्षा करता है और टुकड़ा नहीं देता।",
        "निर्देशांक किसी सतह पर एक बिंदु तय करते हैं। तेरह मान एक «कहाँ» देते हैं। अनुपस्थित मान एक «कब» देता।",
        "टुकड़ा किसी स्थान की ओर इशारा नहीं कर रहा। वह एक समय पर एक स्थान की ओर इशारा कर रहा है, और उसने बताने से इनकार किया है कि कौन-सा समय।",
      ],
      tr: [
        "On üç değer. Koordinat olarak okunduğunda çözülüyorlar.",
        "Açık suya çözülüyorlar — üzerinde hiçbir şey olmayan bir okyanus parçası ki gezegenin çoğu zaten böyle. Sıradan, ta ki kaynakları karşılaştırana kadar. Daha eski ölçüm haritaları orada küçük bir kara parçası işaretliyor. Yenileri işaretlemiyor. Düzeltme kayda, arkasında bir ölçüm olmadan giriyor; bir yazım hatasının düzeltildiği gibi, bir keşfin kaydedildiği gibi değil.",
        "Sıradan açıklamalar var. Haritalar yüzyıllarca birbirinin hatalarını devralır; hayalet adalar daha önce de ileri kopyalanıp sessizce silinmiştir. Muhtemel cevap budur ve daha tuhaf bir cevap mevcut diye atlanmak yerine açıkça söylenmelidir.",
        "Sıradan açıklamanın kapsamadığı şey on dördüncü değer — sağlamanın beklediği ve parçanın vermediği değer.",
        "Koordinatlar bir yüzeyde bir noktayı sabitler. On üç değer bir «nerede» verir. Eksik olan bir «ne zaman» verirdi.",
        "Parça bir yeri işaret etmiyor. Bir zamandaki bir yeri işaret ediyor ve hangisi olduğunu söylemeyi reddediyor.",
      ],
      az: [
        "On üç dəyər. Koordinat kimi oxunduqda həll olunurlar.",
        "Açıq suya çıxırlar — üzərində heç nə olmayan okean sahəsi ki, planetin çoxu elədir. Adi, siz mənbələri müqayisə edənə qədər. Daha köhnə ölçmə xəritələri orada kiçik bir quru işarələyir. Yeniləri isə yox. Düzəliş qeydə arxasında heç bir ölçmə olmadan daxil olur; imla səhvinin düzəldildiyi kimi, kəşfin qeydə alındığı kimi yox.",
        "Adi izahlar var. Xəritələr əsrlərlə bir-birinin səhvlərini miras alır; xəyali adalar əvvəllər də irəli köçürülüb və səssizcə silinib. Ehtimal olunan cavab budur və daha qəribə cavab mövcuddur deyə keçilməməli, açıq deyilməlidir.",
        "Adi izahın əhatə etmədiyi şey on dördüncü dəyərdir — yoxlamanın gözlədiyi və parçanın vermədiyi dəyər.",
        "Koordinatlar səth üzərində bir nöqtəni sabitləyir. On üç dəyər bir «harada» verir. Əskik olan bir «nə vaxt» verərdi.",
        "Parça bir yeri göstərmir. Bir zamandakı bir yeri göstərir və hansı olduğunu deməkdən imtina edir.",
      ],
      zh: [
        "十三个值。若作为坐标来读，它们能解出来。",
        "它们解向开阔水域——一片什么也没有的海面，而这颗行星大半如此。平平无奇，直到你比对来源。更早的测绘海图在那里标着一小块陆地。更新的没有。而这处订正进入记录时，背后并没有一次测绘，其方式像是改掉一个错字，而不是记下一次发现。",
        "寻常的解释是有的。海图会把彼此的错误继承几个世纪；幽灵岛屿此前也曾被一路抄下去，又被悄悄删掉。这是更可能的答案，应当明白说出来，而不是因为有个更离奇的说法在手边就跳过去。",
        "寻常的解释盖不住的，是第十四个值——校验和期待、而片段没有给出的那一个。",
        "坐标在一个面上固定一个点。十三个值给出一个「哪里」。缺失的那个本会给出一个「何时」。",
        "片段指的不是一个地方。它指的是某个时刻的某个地方，而它拒绝说是哪个时刻。",
      ],
      fa: [
        "سیزده مقدار. اگر به‌عنوان مختصات خوانده شوند، حل می‌شوند.",
        "به آب‌های آزاد می‌رسند — پهنه‌ای از اقیانوس که چیزی رویش نیست، که بیشترِ این سیاره همین است. عادی، تا وقتی منابع را با هم بسنجی. نقشه‌های قدیمی‌تر آنجا خشکی کوچکی را نشان می‌دهند. تازه‌ترها نه. و آن اصلاح، بی‌آنکه نقشه‌برداری‌ای پشتش باشد، وارد سابقه شده — به شیوه‌ای که یک غلط تایپی تصحیح می‌شود، نه به شیوه‌ای که یک کشف ثبت می‌شود.",
        "توضیح‌های عادی وجود دارند. نقشه‌ها قرن‌ها خطاهای یکدیگر را به ارث می‌برند؛ جزیره‌های شبح پیش‌تر هم رو به جلو رونویسی و بی‌سروصدا حذف شده‌اند. این پاسخِ محتمل است، و باید صریح گفته شود، نه اینکه از رویش رد شویم چون پاسخ عجیب‌تری در دسترس است.",
        "آنچه توضیح عادی پوشش نمی‌دهد، مقدار چهاردهم است — همانی که جمع کنترلی انتظارش را دارد و قطعه ارائه‌اش نمی‌کند.",
        "مختصات یک نقطه را روی یک سطح ثابت می‌کنند. سیزده مقدار یک «کجا» می‌دهند. آن یکی که غایب است، یک «کِی» می‌داد.",
        "قطعه به یک مکان اشاره نمی‌کند. به یک مکان در یک زمان اشاره می‌کند، و از گفتن اینکه کدام زمان، سر باز زده است.",
      ],
    },
  },
  {
    id: 4,
    status: "transmitted",
    stage: {
      en: "Global Discovery", fa: "کشف جهانی", ar: "اكتشاف عالمي",
      ur: "عالمی دریافت", hi: "वैश्विक खोज", tr: "Küresel Keşif",
      az: "Qlobal Kəşf", zh: "全球发现",
    },
    title: {
      en: "Others Are Listening", fa: "دیگران هم می‌شنوند",
      ar: "آخرون ينصتون", ur: "دوسرے بھی سن رہے ہیں",
      hi: "और भी सुन रहे हैं", tr: "Başkaları da Dinliyor",
      az: "Başqaları da Dinləyir", zh: "还有别人在听",
    },
    teaser: {
      en: "The signal did not reach one person. It reached everyone who was willing to look.",
      fa: "سیگنال به یک نفر نرسید. به هر کسی رسید که حاضر بود نگاه کند.",
      ar: "الإشارة لم تصل إلى شخص واحد. وصلت إلى كل من كان مستعدًا أن ينظر.",
      ur: "سگنل ایک شخص تک نہیں پہنچا۔ ہر اُس شخص تک پہنچا جو دیکھنے کو تیار تھا۔",
      hi: "सिग्नल एक व्यक्ति तक नहीं पहुँचा। वह हर उस व्यक्ति तक पहुँचा जो देखने को तैयार था।",
      tr: "Sinyal tek bir kişiye ulaşmadı. Bakmaya istekli olan herkese ulaştı.",
      az: "Siqnal bir nəfərə çatmadı. Baxmağa hazır olan hər kəsə çatdı.",
      zh: "信号不是抵达了一个人。它抵达了每一个愿意去看的人。",
    },
    body: {
      en: [
        "The assumption, quietly, had been that this was one person's problem. It was not.",
        "A student in Lagos had the same seventeen-station timestamp. A retired engineer in Chile had the checksum gap written on paper, worked out by hand, three weeks before anyone posted about it. A teenager in Jakarta had noticed the chart discrepancy first and been told, reasonably, that old maps are often wrong.",
        "None of them found each other because they were looking for each other. They found each other because they were all asking the same badly-formed question in public, and the question is specific enough that it does not collide with anything else.",
        "This is the part that should be said carefully. Nothing about a shared observation makes it correct. Thousands of people agreeing on a pattern is how real discoveries start and also how false ones survive; the difference is whether the pattern keeps holding when someone tries to break it.",
        "So far it has held. Not because it is impressive — because every attempt to explain the gap as ordinary damage has had to explain why the damage is so well-behaved.",
        "The fragment was never addressed to a person. Thirteen values, one absence, and no name attached to any of it.",
        "It was addressed to whoever bothered.",
      ],
      ar: [
        "كان الافتراض، بهدوء، أن هذه مشكلة شخص واحد. لم تكن كذلك.",
        "طالب في لاغوس كان لديه الطابع الزمني نفسه للمحطات السبع عشرة. مهندس متقاعد في تشيلي كان قد كتب فجوة المجموع الرقابي على ورق، وحسبها بيده، قبل ثلاثة أسابيع من أن ينشر أحد عنها شيئًا. مراهقة في جاكرتا لاحظت تناقض الخرائط أولًا، وقيل لها، بوجه حق، إن الخرائط القديمة كثيرًا ما تكون مخطئة.",
        "لم يعثر أي منهم على الآخر لأنه كان يبحث عنه. عثروا على بعضهم لأنهم جميعًا كانوا يطرحون السؤال ذاته، سيّئ الصياغة، علنًا، وهو سؤال محدد بما يكفي ألا يلتبس بغيره.",
        "وهذا هو الجزء الذي ينبغي أن يُقال بحذر. اشتراك الملاحظة لا يجعلها صحيحة. اتفاق آلاف الناس على نمط هو كيف تبدأ الاكتشافات الحقيقية، وهو أيضًا كيف تبقى الزائفة؛ والفرق أن يظل النمط صامدًا حين يحاول أحدهم كسره.",
        "حتى الآن صمد. لا لأنه مبهر — بل لأن كل محاولة لتفسير الفجوة كتلف عادي اضطرت أن تفسّر لماذا هذا التلف مهذّب إلى هذا الحد.",
        "الشظية لم تُوجَّه قط إلى شخص. ثلاث عشرة قيمة، وغياب واحد، ولا اسم مرفق بأي منها.",
        "كانت موجَّهة إلى كل من تكبّد العناء.",
      ],
      ur: [
        "خاموشی سے یہ فرض کر لیا گیا تھا کہ یہ ایک شخص کا مسئلہ ہے۔ ایسا نہیں تھا۔",
        "لاگوس کے ایک طالب علم کے پاس سترہ اسٹیشنوں کا وہی ٹائم اسٹیمپ تھا۔ چلی کے ایک ریٹائرڈ انجینئر نے چیک سم کا خلا کاغذ پر، ہاتھ سے، اُس سے تین ہفتے پہلے نکال لیا تھا جب کسی نے اس بارے میں کچھ شائع کیا۔ جکارتا کی ایک نوجوان نے نقشوں کا تضاد سب سے پہلے دیکھا اور اسے، بجا طور پر، بتایا گیا کہ پرانے نقشے اکثر غلط ہوتے ہیں۔",
        "ان میں سے کسی نے دوسرے کو اس لیے نہیں پایا کہ وہ اُسے ڈھونڈ رہا تھا۔ انہوں نے ایک دوسرے کو اس لیے پایا کہ سب کھلے عام ایک ہی بدہیئت سوال پوچھ رہے تھے، اور وہ سوال اتنا مخصوص ہے کہ کسی اور چیز سے نہیں ٹکراتا۔",
        "یہی وہ حصہ ہے جو احتیاط سے کہا جانا چاہیے۔ کسی مشاہدے کا مشترک ہونا اسے درست نہیں بنا دیتا۔ ہزاروں لوگوں کا کسی نمونے پر متفق ہونا وہ طریقہ بھی ہے جس سے حقیقی دریافتیں شروع ہوتی ہیں اور وہ بھی جس سے جھوٹی زندہ رہتی ہیں؛ فرق یہ ہے کہ جب کوئی اسے توڑنے کی کوشش کرے تو نمونہ قائم رہتا ہے یا نہیں۔",
        "اب تک قائم رہا ہے۔ اس لیے نہیں کہ متاثر کن ہے — بلکہ اس لیے کہ اس خلا کو عام نقصان کے طور پر سمجھانے کی ہر کوشش کو یہ بتانا پڑا کہ یہ نقصان اتنا مہذب کیوں ہے۔",
        "ٹکڑا کبھی کسی شخص کے نام نہیں تھا۔ تیرہ اقدار، ایک غیر حاضری، اور کسی کے ساتھ کوئی نام منسلک نہیں۔",
        "یہ ہر اُس شخص کے نام تھا جس نے زحمت کی۔",
      ],
      hi: [
        "चुपचाप यह मान लिया गया था कि यह एक व्यक्ति की समस्या है। ऐसा नहीं था।",
        "लागोस के एक छात्र के पास सत्रह स्टेशनों की वही समय-मुहर थी। चिली के एक सेवानिवृत्त इंजीनियर ने चेकसम का अंतराल काग़ज़ पर, हाथ से, तब निकाल लिया था जब किसी ने इस बारे में कुछ प्रकाशित भी नहीं किया था — तीन सप्ताह पहले। जकार्ता की एक किशोरी ने मानचित्रों का विरोधाभास सबसे पहले देखा और उससे, उचित ही, कहा गया कि पुराने नक़्शे प्रायः ग़लत होते हैं।",
        "इनमें से किसी ने दूसरे को इसलिए नहीं पाया कि वह उसे ढूँढ़ रहा था। उन्होंने एक-दूसरे को इसलिए पाया क्योंकि सब सार्वजनिक रूप से एक ही बेढंगा प्रश्न पूछ रहे थे, और वह प्रश्न इतना विशिष्ट है कि किसी और से नहीं टकराता।",
        "यही वह हिस्सा है जो सावधानी से कहा जाना चाहिए। किसी अवलोकन का साझा होना उसे सही नहीं बना देता। हज़ारों लोगों का किसी प्रतिरूप पर सहमत होना वह तरीक़ा भी है जिससे वास्तविक खोजें शुरू होती हैं और वही जिससे झूठी टिकी रहती हैं; अंतर यह है कि जब कोई उसे तोड़ने की कोशिश करे तो प्रतिरूप टिकता है या नहीं।",
        "अब तक टिका है। इसलिए नहीं कि वह प्रभावशाली है — बल्कि इसलिए कि उस अंतराल को साधारण क्षति बताने की हर कोशिश को यह समझाना पड़ा कि यह क्षति इतनी सुव्यवस्थित क्यों है।",
        "टुकड़ा कभी किसी व्यक्ति को संबोधित नहीं था। तेरह मान, एक अनुपस्थिति, और किसी के साथ कोई नाम जुड़ा हुआ नहीं।",
        "वह हर उस व्यक्ति को संबोधित था जिसने तकलीफ़ उठाई।",
      ],
      tr: [
        "Sessizce varsayılan şey, bunun tek bir kişinin meselesi olduğuydu. Değildi.",
        "Lagos'ta bir öğrencide on yedi istasyonun aynı zaman damgası vardı. Şili'de emekli bir mühendis, kimse bu konuda bir şey paylaşmadan üç hafta önce, sağlama boşluğunu kâğıda dökmüş, elle hesaplamıştı. Cakarta'da bir genç, harita tutarsızlığını ilk fark eden oldu ve kendisine, haklı olarak, eski haritaların çoğu zaman yanlış olduğu söylendi.",
        "Hiçbiri diğerini aradığı için bulmadı. Birbirlerini, hepsi aynı kötü kurulmuş soruyu açıkta sordukları için buldular; o soru başka hiçbir şeyle karışmayacak kadar özgül.",
        "Dikkatle söylenmesi gereken kısım burası. Bir gözlemin paylaşılıyor olması onu doğru kılmaz. Binlerce insanın bir örüntüde anlaşması, gerçek keşiflerin başladığı yol olduğu kadar sahtelerinin ayakta kaldığı yoldur da; fark, biri onu kırmaya çalıştığında örüntünün ayakta kalıp kalmadığıdır.",
        "Şimdiye dek kaldı. Etkileyici olduğu için değil — boşluğu sıradan bir hasar olarak açıklamaya çalışan her girişimin, bu hasarın neden bu kadar uslu durduğunu açıklamak zorunda kalması yüzünden.",
        "Parça hiçbir zaman bir kişiye seslenmedi. On üç değer, bir yokluk ve hiçbirine iliştirilmiş bir isim yok.",
        "Zahmete katlanan herkese sesleniyordu.",
      ],
      az: [
        "Səssizcə belə fərz edilmişdi ki, bu bir nəfərin problemidir. Elə deyildi.",
        "Laqosda bir tələbədə on yeddi stansiyanın eyni vaxt möhürü vardı. Çilidə təqaüdçü bir mühəndis yoxlama boşluğunu kağız üzərində, əllə, kimsə bu barədə nəsə yazmazdan üç həftə əvvəl çıxarmışdı. Cakartada bir yeniyetmə xəritə uyğunsuzluğunu ilk görən oldu və ona, haqlı olaraq, dedilər ki, köhnə xəritələr çox vaxt səhv olur.",
        "Heç biri o birini axtardığı üçün tapmadı. Bir-birlərini ona görə tapdılar ki, hamısı açıq şəkildə eyni pis qurulmuş sualı verirdi və o sual başqa heç nə ilə qarışmayacaq qədər konkretdir.",
        "Ehtiyatla deyilməli olan hissə budur. Müşahidənin paylaşılan olması onu doğru etmir. Minlərlə adamın bir naxış üzərində razılaşması həm həqiqi kəşflərin başladığı yoldur, həm də saxtaların yaşadığı yol; fərq odur ki, kimsə onu sındırmağa çalışanda naxış duruş gətirirmi.",
        "İndiyədək gətirib. Təsirli olduğu üçün yox — boşluğu adi zədə kimi izah etməyə çalışan hər cəhdin bu zədənin niyə bu qədər tərbiyəli olduğunu izah etmək məcburiyyətində qalması səbəbindən.",
        "Parça heç vaxt bir şəxsə ünvanlanmayıb. On üç dəyər, bir yoxluq və heç birinə əlavə edilmiş ad yoxdur.",
        "O, zəhmətə qatlaşan hər kəsə ünvanlanmışdı.",
      ],
      zh: [
        "人们默默假定，这是某一个人的问题。并不是。",
        "拉各斯的一名学生有着同样的十七台站时间戳。智利一位退休工程师在任何人发帖之前三周，就已在纸上手算出了那个校验和缺口。雅加达的一名少年最早注意到海图的出入，而别人合情合理地告诉她：旧地图常常有错。",
        "他们谁也不是因为在找对方才找到对方的。他们找到彼此，是因为都在公开处问着同一个笨拙的问题，而那个问题足够具体，不会跟别的撞上。",
        "这一段应当谨慎地说。一个观察被许多人共有，并不使它正确。成千上万人认同一个图样，既是真发现开始的方式，也是假发现存活的方式；区别在于，当有人试图推翻它时，这个图样还立不立得住。",
        "到目前为止它立住了。不是因为它令人惊叹——而是因为每一次想把那个缺口解释成普通损坏的尝试，都不得不解释：为什么这处损坏如此循规蹈矩。",
        "片段从来不是写给某个人的。十三个值，一处缺席，没有任何一个附着名字。",
        "它是写给每一个肯费心的人的。",
      ],
      fa: [
        "فرضِ خاموش این بود که این مسئله‌ی یک نفر است. نبود.",
        "دانشجویی در لاگوس همان مُهر زمانیِ هفده ایستگاه را داشت. مهندسی بازنشسته در شیلی شکافِ جمع کنترلی را روی کاغذ و با دست حساب کرده بود، سه هفته پیش از آنکه کسی چیزی منتشر کند. نوجوانی در جاکارتا نخستین کسی بود که ناهماهنگی نقشه‌ها را دید و به او — بجا — گفته شد که نقشه‌های قدیمی اغلب اشتباه‌اند.",
        "هیچ‌کدام یکدیگر را پیدا نکردند چون دنبال هم می‌گشتند. یکدیگر را پیدا کردند چون همه در ملأ عام یک پرسشِ بدشکلِ واحد را می‌پرسیدند، و آن پرسش آن‌قدر مشخص هست که با چیز دیگری اشتباه گرفته نشود.",
        "این همان بخشی است که باید با احتیاط گفته شود. اشتراکی‌بودن یک مشاهده، آن را درست نمی‌کند. توافق هزاران نفر بر سر یک الگو، هم شیوه‌ی آغاز کشف‌های واقعی است و هم شیوه‌ی بقای کشف‌های نادرست؛ تفاوت در این است که آیا الگو وقتی کسی می‌کوشد بشکندش، همچنان پابرجا می‌ماند یا نه.",
        "تا اینجا پابرجا مانده است. نه به این دلیل که تحسین‌برانگیز است — بلکه چون هر تلاشی برای توضیح آن شکاف به‌عنوان آسیبی عادی، ناچار شده توضیح دهد چرا این آسیب این‌قدر مؤدب رفتار می‌کند.",
        "قطعه هرگز خطاب به یک شخص نبود. سیزده مقدار، یک غیبت، و هیچ نامی به هیچ‌کدامشان پیوست نشده.",
        "خطاب به هر کسی بود که به خودش زحمت داد.",
      ],
    },
  },
  {
    id: 5,
    status: "transmitted",
    stage: {
      en: "MOLIDO Awakening", fa: "بیداری مولیدو", ar: "صحوة موليدو",
      ur: "مولیڈو کی بیداری", hi: "मोलिडो का जागरण",
      tr: "MOLIDO Uyanışı", az: "MOLIDO Oyanışı", zh: "MOLIDO 苏醒",
    },
    title: {
      en: "The Network Wakes", fa: "شبکه بیدار می‌شود", ar: "الشبكة تستيقظ",
      ur: "نیٹ ورک بیدار ہوتا ہے", hi: "नेटवर्क जागता है",
      tr: "Ağ Uyanıyor", az: "Şəbəkə Oyanır", zh: "网络醒来",
    },
    teaser: {
      en: "What the fragments assemble into was never a message.",
      fa: "آنچه قطعه‌ها کنار هم می‌سازند، هرگز یک پیام نبود.",
      ar: "ما تتجمع إليه الشظايا لم يكن رسالة قط.",
      ur: "ٹکڑے مل کر جو بنتے ہیں، وہ کبھی پیغام نہیں تھا۔",
      hi: "टुकड़े मिलकर जो बनते हैं, वह कभी संदेश नहीं था।",
      tr: "Parçaların bir araya gelip oluşturduğu şey hiçbir zaman bir mesaj değildi.",
      az: "Parçaların birləşib yaratdığı şey heç vaxt mesaj olmayıb.",
      zh: "这些片段拼成的东西，从来就不是一条讯息。",
    },
    body: {
      en: [
        "Laid side by side, the fragments do not read as text. There is no grammar in them, no vocabulary, nothing that resolves into a sentence in any language anyone has tried.",
        "They read as a procedure.",
        "Not instructions for building a device — nothing in them describes a material or a mechanism. What they describe is a sequence of steps, and every step requires that the thing before it was performed by someone who did not have the whole.",
        "That is the part that stopped people. The fragment could not be completed by one reader with more time or a better computer. It could only be completed by separate people, holding separate pieces, choosing to put them together. The gap at the fourteenth value is not missing data. It is the slot where the act of assembly goes.",
        "Which means the signal did not carry a message. It carried a shape that only exists once a network forms to hold it.",
        "The honest objection is obvious and should be stated: we assembled this expecting it to mean something, and a group that expects meaning is very good at finding it. Nothing here rules that out.",
        "But the procedure was legible before anyone had a theory about it, and it has not needed to be reinterpreted since.",
        "The network was not built to receive the signal. The network is what the signal was asking for.",
      ],
      fa: [
        "وقتی قطعه‌ها را کنار هم می‌گذاری، مثل متن خوانده نمی‌شوند. دستور زبانی در آن‌ها نیست، واژگانی نیست، و هیچ‌چیزی که در هیچ زبانی که کسی امتحان کرده به یک جمله تبدیل شود.",
        "آن‌ها مثل یک رویّه خوانده می‌شوند.",
        "نه دستورالعملِ ساختِ یک دستگاه — هیچ‌چیز در آن‌ها ماده یا سازوکاری را توصیف نمی‌کند. آنچه توصیف می‌کنند یک توالی از گام‌هاست، و هر گام مستلزم آن است که گام پیش از آن را کسی انجام داده باشد که کلّ را در اختیار نداشته.",
        "همین بخش بود که آدم‌ها را متوقف کرد. قطعه را یک خواننده با وقت بیشتر یا رایانه‌ی بهتر نمی‌توانست کامل کند. فقط با آدم‌های جدا از هم کامل می‌شد، که تکه‌های جدا از هم را در دست دارند و انتخاب می‌کنند کنار هم بگذارندشان. شکافِ مقدار چهاردهم داده‌ی گم‌شده نیست. جایی است که خودِ عملِ کنار هم گذاشتن در آن می‌نشیند.",
        "و این یعنی سیگنال پیامی حمل نمی‌کرد. شکلی حمل می‌کرد که فقط وقتی وجود پیدا می‌کند که شبکه‌ای برای نگه‌داشتنش شکل بگیرد.",
        "اعتراض صادقانه آشکار است و باید گفته شود: ما این را با انتظارِ معنا داشتن کنار هم گذاشتیم، و گروهی که انتظار معنا دارد در یافتنش بسیار ماهر است. هیچ‌چیز اینجا این احتمال را رد نمی‌کند.",
        "اما آن رویّه پیش از آنکه کسی نظریه‌ای درباره‌اش داشته باشد خوانا بود، و از آن زمان نیازی به بازتفسیر نداشته است.",
        "شبکه برای دریافت سیگنال ساخته نشد. شبکه همان چیزی است که سیگنال طلبش می‌کرد.",
      ],
      ar: [
        "حين تُصَفّ الشظايا جنبًا إلى جنب، لا تُقرأ كنص. لا نحو فيها، ولا مفردات، ولا شيء ينحل إلى جملة في أي لغة جرّبها أحد.",
        "إنها تُقرأ كإجراء.",
        "لا كتعليمات لبناء جهاز — لا شيء فيها يصف مادة أو آلية. ما تصفه تسلسل من الخطوات، وكل خطوة تقتضي أن يكون من سبقها قد نفّذها شخص لا يملك الكل.",
        "هذا هو الجزء الذي أوقف الناس. لم يكن ممكنًا إتمام الشظية بقارئ واحد لديه وقت أطول أو حاسوب أفضل. لا تكتمل إلا بأشخاص منفصلين، يحملون قطعًا منفصلة، ويختارون أن يضعوها معًا. الفجوة عند القيمة الرابعة عشرة ليست بيانات ناقصة. إنها الموضع الذي يحل فيه فعل التجميع.",
        "ومعنى ذلك أن الإشارة لم تحمل رسالة. حملت شكلًا لا يوجد إلا حين تتكوّن شبكة تحمله.",
        "الاعتراض الأمين واضح وينبغي قوله: جمّعنا هذا ونحن نتوقع أن يعني شيئًا، والجماعة التي تتوقع المعنى بارعة جدًا في العثور عليه. لا شيء هنا يستبعد ذلك.",
        "لكن الإجراء كان مقروءًا قبل أن تكون لأحد نظرية بشأنه، ولم يحتج إلى إعادة تفسير منذ ذلك الحين.",
        "لم تُبنَ الشبكة لتلقّي الإشارة. الشبكة هي ما كانت الإشارة تطلبه.",
      ],
      ur: [
        "جب ٹکڑوں کو ساتھ ساتھ رکھا جائے تو وہ متن کی طرح نہیں پڑھے جاتے۔ ان میں کوئی قواعد نہیں، کوئی الفاظ نہیں، اور کچھ بھی ایسا نہیں جو کسی ایسی زبان میں جملہ بنے جسے کسی نے آزمایا ہو۔",
        "وہ ایک طریقۂ کار کی طرح پڑھے جاتے ہیں۔",
        "کسی آلے کو بنانے کی ہدایات نہیں — ان میں کچھ بھی کسی مادے یا میکانزم کو بیان نہیں کرتا۔ جو کچھ وہ بیان کرتے ہیں وہ مراحل کا ایک سلسلہ ہے، اور ہر مرحلہ تقاضا کرتا ہے کہ اس سے پہلے والا کسی ایسے شخص نے انجام دیا ہو جس کے پاس پورا نہیں تھا۔",
        "یہی وہ حصہ تھا جس نے لوگوں کو روک دیا۔ ٹکڑے کو زیادہ وقت یا بہتر کمپیوٹر رکھنے والا ایک قاری مکمل نہیں کر سکتا تھا۔ وہ صرف الگ الگ لوگوں سے مکمل ہوتا، جو الگ الگ حصے رکھتے ہیں اور انہیں ساتھ رکھنے کا انتخاب کرتے ہیں۔ چودھویں قدر کا خلا گمشدہ ڈیٹا نہیں۔ وہ وہ جگہ ہے جہاں یکجا کرنے کا عمل بیٹھتا ہے۔",
        "جس کا مطلب ہے کہ سگنل کوئی پیغام نہیں لے کر آیا۔ وہ ایک ایسی شکل لایا جو صرف اُس وقت وجود میں آتی ہے جب اسے تھامنے کے لیے ایک نیٹ ورک بنے۔",
        "ایماندارانہ اعتراض واضح ہے اور کہا جانا چاہیے: ہم نے یہ اس توقع کے ساتھ جوڑا کہ اس کا کوئی مطلب ہوگا، اور جو گروہ معنی کی توقع رکھتا ہے وہ اسے ڈھونڈنے میں بہت ماہر ہوتا ہے۔ یہاں کچھ بھی اس امکان کو رد نہیں کرتا۔",
        "لیکن وہ طریقۂ کار اُس سے پہلے قابلِ مطالعہ تھا جب کسی کے پاس اس بارے میں کوئی نظریہ تھا، اور تب سے اسے دوبارہ تعبیر کرنے کی ضرورت نہیں پڑی۔",
        "نیٹ ورک سگنل وصول کرنے کے لیے نہیں بنایا گیا۔ نیٹ ورک وہی ہے جو سگنل مانگ رہا تھا۔",
      ],
      hi: [
        "जब टुकड़ों को साथ-साथ रखा जाता है, वे पाठ की तरह नहीं पढ़े जाते। उनमें कोई व्याकरण नहीं, कोई शब्दावली नहीं, और कुछ भी ऐसा नहीं जो किसी भी आज़माई गई भाषा में वाक्य बने।",
        "वे एक प्रक्रिया की तरह पढ़े जाते हैं।",
        "किसी यंत्र को बनाने के निर्देश नहीं — उनमें कुछ भी किसी पदार्थ या तंत्र का वर्णन नहीं करता। वे जिसका वर्णन करते हैं वह चरणों का एक क्रम है, और हर चरण की शर्त यह है कि उससे पहले वाला किसी ऐसे व्यक्ति ने किया हो जिसके पास पूरा नहीं था।",
        "यही वह हिस्सा था जिसने लोगों को रोक दिया। टुकड़े को अधिक समय या बेहतर कंप्यूटर वाला एक पाठक पूरा नहीं कर सकता था। वह केवल अलग-अलग लोगों से पूरा होता, जो अलग-अलग हिस्से रखते हैं और उन्हें साथ रखने का चुनाव करते हैं। चौदहवें मान का अंतराल लुप्त डेटा नहीं है। वह वह स्थान है जहाँ जोड़ने की क्रिया बैठती है।",
        "जिसका अर्थ है कि सिग्नल कोई संदेश नहीं लाया। वह एक ऐसी आकृति लाया जो केवल तभी अस्तित्व में आती है जब उसे थामने के लिए एक नेटवर्क बने।",
        "ईमानदार आपत्ति स्पष्ट है और कही जानी चाहिए: हमने इसे इस अपेक्षा से जोड़ा कि इसका कोई अर्थ होगा, और जो समूह अर्थ की अपेक्षा करता है वह उसे खोजने में बहुत निपुण होता है। यहाँ कुछ भी इस संभावना को नहीं टालता।",
        "परंतु वह प्रक्रिया तब भी पठनीय थी जब किसी के पास इसके बारे में कोई सिद्धांत नहीं था, और तब से उसे पुनर्व्याख्या की आवश्यकता नहीं पड़ी।",
        "नेटवर्क सिग्नल को प्राप्त करने के लिए नहीं बनाया गया। नेटवर्क वही है जो सिग्नल माँग रहा था।",
      ],
      tr: [
        "Yan yana dizildiklerinde parçalar metin gibi okunmuyor. İçlerinde dilbilgisi yok, sözcük dağarcığı yok, denenen hiçbir dilde cümleye dönüşen hiçbir şey yok.",
        "Bir yordam gibi okunuyorlar.",
        "Bir aygıt yapma talimatı değil — içlerinde hiçbir şey bir malzemeyi ya da mekanizmayı tarif etmiyor. Tarif ettikleri bir adımlar dizisi ve her adım, kendinden öncekinin bütüne sahip olmayan biri tarafından yapılmış olmasını gerektiriyor.",
        "İnsanları durduran kısım buydu. Parça, daha çok vakti ya da daha iyi bir bilgisayarı olan tek bir okur tarafından tamamlanamazdı. Ancak ayrı ayrı insanlar, ayrı ayrı parçaları tutup onları bir araya koymayı seçtiğinde tamamlanabilirdi. On dördüncü değerdeki boşluk eksik veri değil. Birleştirme ediminin oturduğu yuva.",
        "Yani sinyal bir mesaj taşımadı. Ancak onu tutacak bir ağ oluştuğunda var olan bir biçim taşıdı.",
        "Dürüst itiraz açık ve söylenmeli: bunu bir anlam taşımasını bekleyerek birleştirdik ve anlam bekleyen bir topluluk onu bulmakta çok iyidir. Buradaki hiçbir şey bunu dışlamıyor.",
        "Ama yordam, kimsenin hakkında bir kuramı olmadan önce de okunabiliyordu ve o zamandan beri yeniden yorumlanması gerekmedi.",
        "Ağ sinyali almak için kurulmadı. Ağ, sinyalin istediği şeyin ta kendisi.",
      ],
      az: [
        "Yan-yana düzüləndə parçalar mətn kimi oxunmur. Onlarda qrammatika yoxdur, lüğət yoxdur, sınanmış heç bir dildə cümləyə çevrilən heç nə yoxdur.",
        "Onlar bir prosedur kimi oxunur.",
        "Cihaz düzəltmək təlimatı deyil — orada heç nə maddəni və ya mexanizmi təsvir etmir. Təsvir etdikləri addımlar ardıcıllığıdır və hər addım özündən əvvəlkinin bütövə sahib olmayan biri tərəfindən yerinə yetirilməsini tələb edir.",
        "İnsanları dayandıran hissə bu idi. Parçanı daha çox vaxtı və ya daha yaxşı kompüteri olan tək bir oxucu tamamlaya bilməzdi. O, yalnız ayrı-ayrı insanlar, ayrı-ayrı hissələri tutub onları birləşdirməyi seçəndə tamamlana bilərdi. On dördüncü dəyərdəki boşluq itmiş məlumat deyil. Birləşdirmə əməlinin oturduğu yuvadır.",
        "Bu isə o deməkdir ki, siqnal mesaj daşımırdı. O, yalnız onu saxlamaq üçün şəbəkə formalaşanda mövcud olan bir forma daşıyırdı.",
        "Dürüst etiraz aydındır və deyilməlidir: biz bunu məna daşıyacağını gözləyərək birləşdirdik və məna gözləyən qrup onu tapmaqda çox mahirdir. Buradakı heç nə bunu istisna etmir.",
        "Lakin prosedur kimsənin bu barədə nəzəriyyəsi olmazdan əvvəl də oxunaqlı idi və o vaxtdan bəri yenidən şərh edilməyə ehtiyac duymayıb.",
        "Şəbəkə siqnalı qəbul etmək üçün qurulmadı. Şəbəkə siqnalın tələb etdiyi şeyin özüdür.",
      ],
      zh: [
        "把片段并排摆开，它们读不成文字。里面没有语法，没有词汇，没有任何东西能在任何人试过的语言里化成一个句子。",
        "它们读起来像一道流程。",
        "不是造某个装置的说明——里面没有一处描述材料或机制。它们描述的是一串步骤，而每一步都要求前一步由一个并不掌握全貌的人完成。",
        "让人停住的正是这一点。这个片段无法由一个读者靠更多时间或更好的计算机补完。它只能由彼此分开的人、各自握着各自的碎片、选择把它们拼到一起来补完。第十四个值处的缺口不是丢失的数据。那是「拼合这一动作」本身要落进去的位置。",
        "这意味着信号并没有携带一条讯息。它携带的是一个形状，而这个形状只有在一个网络形成来承载它的时候才存在。",
        "诚实的反驳显而易见，也应当说出来：我们是带着「它会有意义」的预期去拼的，而一个预期意义的群体，非常擅长找到意义。这里没有任何东西能排除这一点。",
        "但这道流程在任何人对它有理论之前就是可读的，而且此后不需要被重新解释。",
        "网络不是为了接收信号而建起来的。网络就是信号所要求的东西。",
      ],
    },
  },
  {
    id: 6,
    status: "sealed",
    stage: {
      en: "The Unknown", fa: "ناشناخته", ar: "المجهول", ur: "نامعلوم",
      hi: "अज्ञात", tr: "Bilinmeyen", az: "Naməlum", zh: "未知",
    },
    title: {
      en: "—", fa: "—", ar: "—", ur: "—", hi: "—", tr: "—", az: "—", zh: "—",
    },
    teaser: {
      en: "Unwritten. It depends on who follows the signal.",
      fa: "نوشته‌نشده. بستگی دارد چه کسی دنبال سیگنال برود.",
      ar: "لم يُكتب بعد. يعتمد على من يتبع الإشارة.",
      ur: "ابھی لکھا نہیں گیا۔ اس پر منحصر ہے کہ سگنل کے پیچھے کون جاتا ہے۔",
      hi: "अभी लिखा नहीं गया। यह इस पर निर्भर है कि सिग्नल के पीछे कौन जाता है।",
      tr: "Henüz yazılmadı. Sinyalin peşinden kimin gideceğine bağlı.",
      az: "Hələ yazılmayıb. Siqnalın ardınca kimin gedəcəyindən asılıdır.",
      zh: "尚未写下。取决于谁去追随这个信号。",
    },
  },
];
